version: "3"

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
      - "8089:8089/udp"
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}

  chronograf:
    image: chronograf:latest
    container_name: chronograf
    environment:
      - RESOURCES_PATH=/usr/share/chronograf/resources
      - REPORTING_DISABLED=true
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_URL=${INFLUXDB_URL}
    volumes:
      # Mount for chronograf resources
      - ./chronograf:/usr/share/chronograf/resources/
    ports:
      - "8888:8888"
    links:
      - influxdb
    depends_on:
      - influxdb

  forza:
    build: ./forza_telemetry
    image: forza_telemetry:latest
    container_name: forza_telemetry
    ports:
      - "${FORZA_TELEMETRY_PORT}:${FORZA_TELEMETRY_PORT}/udp"
    environment:
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      - INFLUXDB_URL=${INFLUXDB_URL}
    volumes:
      - "./forza_telemetry:/app"
    depends_on:
      - influxdb
    links:
      - influxdb
